App/Cigarettes/Cigarettes.js, App/Home/Home.js, App/Home/utils/pm25ToCigarettes.js
- Closes #1.
- Change Shit to Sh*t.
- "You'll Smoke" vs "You smoked" based on local time, not on measured time.
=> Fix TypeError bug

App/Header/Header.js, app.example.json, package.json, yarn.lock
=> Am bump expo

App/Screens/Home/Home.js, App/utils/theme.js
=> Am fix layout

App/Screens/Home/Cigarettes/Cigarettes.js, App/components/Footer/About/About.js, app.example.json, package.json
- Change app name to "Sh**t! I Smoke"
- Cigarette display bug
=> Small fixes

App/Screens/Screens.js, App/utils/dataSources/aqicn.js, App/utils/dataSources/windWaqi.js, app.example.json, package.json
App crashed when visiting the Map page.
=> Fix Map bug

app.example.json, package.json
=> Bump version

App/components/Header/Header.js, app.example.json, package.json
For geocoding. We passed the Google free tier.
=> Use LocationIQ instead of Google Maps API

App/App.js, README.md, app.example.json, package.json, yarn.lock
=> Add sentry

package.json, yarn.lock
Mobx 5 doesn't work on Android
=> Rollback to mobx 4

App/Screens/Loading/Loading.js, App/Screens/Screens.js, app.example.json, package.json
- Can choose location when denying gps
- Cough loading page shows correct cougs
=> Small bug fixes

App/App.js, App/Screens/ErrorScreen/ErrorScreen.js, App/Screens/Loading/Loading.js, App/Screens/Screens.js, App/Screens/Search/Search.js, App/components/CurrentLocation/CurrentLocation.js, App/stores/error.js, App/stores/index.js
- add technical error message on the Error page
- add some console.logs for debugging
=> feat: add clearer error messages

.babelrc, .editorconfig, .eslintrc, App/Screens/About/About.js, App/Screens/Details/Details.js, App/Screens/Details/Distance/Distance.js, App/Screens/Details/Header/Header.js, App/Screens/ErrorScreen/ErrorScreen.js, App/Screens/Home/Header/Header.js, App/Screens/Home/Home.js, App/Screens/Home/swearWords.js, App/Screens/Loading/Loading.js, App/Screens/Search/Search.js, App/Screens/Search/SearchHeader/SearchHeader.js, App/components/BackButton/BackButton.js, App/localization/index.js, CONTRIBUTING.md, README.md, babel.config.js, package.json, yarn.lock
the current eslint config is prettier+semistandard
=> refactor: Use eslint instead of semistandard

App/Screens/Home/Cigarettes/Cigarettes.js
=> fix: removes undefined style

App/managers/AqiHistoryTask.ts, App/stores/fetchGpsPosition/fetchGpsPosition.ts
=> fix: Make background fetch work

App/Screens/Home/Footer/Footer.tsx
=> fix: Round the cigarettes number when shared

App/Screens/Home/Home.tsx, App/Screens/Home/SelectFrequency/SelectFrequency.tsx, App/Screens/ShareScreen/ShareImage/ShareImage.tsx, App/Screens/ShareScreen/ShareScreen.tsx, App/components/CigaretteBlock/CigaretteBlock.tsx
refactor some code:
- use FrequencyContext directly in `<SelectFrequency />`
- all components in `components/` are pure, not using Context
=> refactor: Use setFrequency in SelectFrequency

package.json
=> feat: Add typechecking on yarn lint (#248)

README.md
=> Fix Algolia places link in readme(#280)

.github/workflows/main.yml
=> chore: Activate Github Actions

README.md, app.example.json
=> chore: Put `null` by default in app.json

.prettierrc.js, App/Screens/Home/AdditionalInfo/AdditionalInfo.tsx, App/Screens/Home/Home.tsx, App/components/CigaretteBlock/CigaretteBlock.tsx, App/stores/api.tsx
Also fix memoizing of historical cigarettes
=> fix: Show isToofar warning on monthly and weekly

.github/workflows/master.yml, .github/workflows/tag.yml, App/Screens/Search/fetchAlgolia.ts, README.md, app.example.json
=> ci: Build binaries on tag

App/Screens/Screens.tsx, package.json, yarn.lock
Changes
1. Added a new `expo-status-bar` package
2. Added the StatusBar from the new Package to `App/Screens/Screens.tsx`
closes #321 
Signed-off-by: sarthakpranesh <sarthak.pranesh2018@vitstudent.ac.in>
=> Added new expo-status-bar package and added the StatusBar in Screen.tsx
